export const TEXT = {
   SIMPLIFIED_REAL_ESTATE :'Simplified Real Estate',
   HOME1: 'A digital way to',
   HOME2: 'buying and selling property',
   I_AM_READY: 'I’m Ready',
   GET_STARTED: 'Get Started',
   typed_animated: 'You are just a few steps away to completing your journey!',
   login_to_continue:'Login to Continue',
   buy_sell_property: 'Are you looking to buy or sell property?',
   great: 'Great',
   provide_contact_info: 'Please provide your contact information.',
   next_question:'Next Question',
   back:'Back',
   login_description_text: ' By entering your contact information, you are providing express written consent for Myte Group to contact you at the email and number you provided via telephone, mobile device, automated means like autodialing, text SMS/MMS and pre-recorded messages, even if you are registered on a corporate, state,or federal Do Not Call list. You are also acknowledging and agreeing to our terms of service and privacy policy. Consent is not required to use our services.',
   property_location: 'What location is your property located in?',
   add: '+ADD',
   property_type: ' What type of property are you wishing to sell?',
   condo: 'Condo',
   revenue_property: 'Revenue Property',
   commercial_or_industrial : 'Commercial or Industrial',
   land_field: 'Land / Field',
   share_info_about_land_field: 'Share info about Land/Field',
   share_info_about_commercial_industry_property: 'Share info about Commercial/Industrial Property',
   submit: 'Submit',
   city_zonage: 'What is the city zonage you have?',
   surface_area: 'What`s the Surface area?',
   agent_call: 'Great! An agent will call you shortly, see you soon!',
   sell_inquiry_options : 'Would you like to dfsds with a free digital home evaluation, or wait for a Call from a real-estate agent?',
   call_from_agent: 'GET CALL FROM AGENT',
   digital_evaluation :'Go With Digital Evaluation',
   sell_upload_tital: 'The more pictures you upload, the more precise our free evaluation will be!',
   choose_file :'Choose files',
   image_file_validation: 'Max you can upload 10 files. 2 MB each image',
   please_choose_file: 'Please choose file',
   continue:'Continue',
   lets_continue: 'LET`S CONTINUE',
   i_am_buyer: 'I`m a Buyer',
   i_am_seller: 'I`m a Seller',
   continue_with_google: 'Continue with Google'
}